---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: template-pii
spec:
  params:
    - name: apikey
      description: The ibmcloud api key
    - name: ibmcloud-api
      description: The ibmcloud api
      default: "https://cloud.ibm.com"
    - name: ibmcloud-region
      description: (Optional) ibmcloud region to use
      default: ""
    - name: pipeline-debug
      description: Toggles debug mode for the pipeline
      default: "0"
    - name: registry-region
      description: (Optional) The ibmcloud container registry region
      default: ""
    - name: resource-group
      description: (Optional) Target resource group (name or id) for the ibmcloud login operation
      default: ""

    # Event params
    - name: branch
      description: The git branch
      default: ""
    - name: commit-id
      description: commit id
      default: ""
    - name: pr-branch
      description: The branch in the forked git repo from where the PR is made
      default: ""
    - name: pr-repository
      description: The forked git repo from where the PR is made
      default: ""
    - name: repository
      description: The git repo
    - name: git-token
      description: The git token

    # Common command related params
    - name: custom-script
      description: (Optional) A custom script to be ran prior to CRA scanning
      default: ""
    - name: env-props
      description: (Optional) A custom configuration of environment properties to source before execution, ex. 'export ABC=123 export DEF=456'
      default: ""
    - name: fileignore
      description: (Optional) Filepath to .fileignore
      default: ""
    - name: ibmcloud-trace
      description: (Optional) Enables IBMCLOUD_TRACE for ibmcloud cli logging
      default: "false"
    - name: output
      description: (Optional) Prints command result to console
      default: "false"
    - name: path
      description: Repository path to scan
      default: "/artifacts"
    - name: strict
      description: (Optional) Enables strict mode for scanning
      default: "false"
    - name: toolchainid
      description: (Optional) The target toolchain id to be used. Defaults to the current toolchain id
      default: ""
    - name: verbose
      description: (Optional) Enable verbose log messages
      default: "false"

    - name: docker-registry-secret
      description: Secret to authenticate for docker-registry-url

  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        API_KEY: $(params.apikey)
        GIT_TOKEN: $(params.git-token)
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: pipeline-pii
        workspaces:
          - name: artifacts
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        params:
          - name: ibmcloud-api
            value: $(params.ibmcloud-api)
          - name: ibmcloud-region
            value: $(params.ibmcloud-region)
          - name: pipeline-debug
            value: $(params.pipeline-debug)
          - name: registry-region
            value: $(params.registry-region)
          - name: resource-group
            value: $(params.resource-group)
          - name: branch
            value: $(params.branch)
          - name: commit-id
            value: $(params.commit-id)
          - name: pr-branch
            value: $(params.pr-branch)
          - name: pr-repository
            value: $(params.pr-repository)
          - name: repository
            value: $(params.repository)
          - name: custom-script
            value: $(params.custom-script)
          - name: env-props
            value: $(params.env-props)
          - name: fileignore
            value: $(params.fileignore)
          - name: ibmcloud-trace
            value: $(params.ibmcloud-trace)
          - name: output
            value: $(params.output)
          - name: path
            value: $(params.path)
          - name: strict
            value: $(params.strict)
          - name: toolchainid
            value: $(params.toolchainid)
          - name: verbose
            value: $(params.verbose)
          
