---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cra-update-pii
spec:
  params:
    # Pipeline related parameters
    - name: continuous-delivery-context-environment
      description: Name of the configmap containing the continuous delivery pipeline context environment properties
      default: environment-properties
    - name: continuous-delivery-context-secret
      description: Reference name for the secret resource
      default: "secure-properties"
    - name: docker-registry-secret
      description: Field in the secret that contains the secret used to login to docker-registry-url
      default: docker-registry-secret
    - name: ibmcloud-api
      description: The ibmcloud api
      default: "https://cloud.ibm.com"
    - name: ibmcloud-apikey-secret-key
      description: Field in the secret that contains the api key used to login to ibmcloud
      default: apikey
    - name: ibmcloud-region
      description: (Optional) ibmcloud region to use
      default: ""
    - name: pipeline-debug
      description: Pipeline debug mode. Value can be 0 or 1
      default: "0"
    - name: registry-region
      description: (Optional) The ibmcloud container registry region
      default: ""
    - name: resource-group
      description: (Optional) Target resource group (name or id) for the ibmcloud login operation
      default: ""
    - name: git-token
      description: Git token required to for GIT operations
      default: ""

  default: "icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.2"

  stepTemplate:
    env:
      - name: PIPELINE_ID
        valueFrom:
          fieldRef:
            fieldPath: metadata.annotations['devops.cloud.ibm.com/pipeline-id']
      - name: PIPELINE_RUN_ID
        valueFrom:
          fieldRef:
            fieldPath: metadata.annotations['devops.cloud.ibm.com/tekton-pipeline']
      - name: PIPELINE_DEBUG
        value: $(params.pipeline-debug)

  steps:
    - name: update-pii
      env:
        - name: GITHUB_READ_TOKEN
          value: $(params.git-token)

        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: $(params.continuous-delivery-context-secret)
              key: $(params.ibmcloud-apikey-secret-key)
              optional: true

      imagePullPolicy: Always
      workingDir: "/artifacts"
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "###### RUNNING PII SCRIPT ######"
          rm -rf node_modules
          export NLS_FOLDER_PATTERN=en
          git clone --depth 1 https://$GITHUB_READ_TOKEN@github.ibm.com/org-ids/pii
          # pii/run
          rm -rf pii # must remove to prevent unintentional side effects in future onepipeline CI tasks e.g. eslint errors in cd-broker in unit tests
          echo "###### DONE PII SCRIPT ######"

      volumeMounts:
        - mountPath: /config
          name: config-volume
        - mountPath: /properties
          name: environment-properties
        - mountPath: /secrets
          name: secure-properties

  workspaces:
    - name: artifacts
      mountPath: /artifacts

  volumes:
    - name: config-volume
      configMap:
        name: toolchain
        items:
          - key: toolchain.json
            path: toolchain.json
    - name: environment-properties
      configMap:
        name: $(params.continuous-delivery-context-environment)
    - name: secure-properties
      secret:
        secretName: $(params.continuous-delivery-context-secret)
